"""Submission ingestion for the Rubric Grading Tool.

v2.2.0 commits 1-4 provide four intentionally separated backend layers:

* normal submissions: canonical LaTeX source, app-compiled visual PDF;
* explicit PDF accommodations: original PDF is authoritative and pages are
  rendered at a deterministic DPI;
* optional assistive handwriting transcription: page-aligned VLM output that
  never replaces the original PDF or rendered page evidence;
* persistent evidence/provenance storage with SHA-256 validation and reusable
  transcription caches.

v2.3.2 adds a source-agnostic canonical submission-domain layer underneath
those existing parsing/evidence APIs. The new ``Submission`` and
``ArtifactFile`` objects describe immutable submission identity/provenance;
``ParsedSubmission`` remains the grading-facing representation of extracted
content.

This package intentionally has no PyQt dependency so its backend can be tested
and reused independently of the desktop UI.
"""

from .compiler import (
    ALLOWED_ENGINES,
    cleanup_compilation_artifacts,
    compile_tex_to_pdf,
)
from .domain import (
    SUBMISSION_DOMAIN_SCHEMA_VERSION,
    ArtifactFile,
    CandidateFile,
    DerivedArtifact,
    ExternalReference,
    ImportBatch,
    ImportCandidate,
    Submission,
    generate_artifact_id,
    generate_candidate_id,
    generate_derived_artifact_id,
    generate_import_batch_id,
    generate_submission_id,
)
from .importer import (
    DUPLICATE_STATUS_EXACT_ACTIVE,
    DUPLICATE_STATUS_EXACT_HISTORICAL,
    DUPLICATE_STATUS_EXISTING_NEW_ATTEMPT,
    DUPLICATE_STATUS_IN_BATCH_EXACT,
    DUPLICATE_STATUS_NONE,
    DUPLICATE_STATUS_NOT_CHECKED,
    DUPLICATE_STATUS_SAME_FILENAMES_CHANGED,
    ImportCommitResult,
    SubmissionImporter,
)
from .latex import (
    extract_text_from_tex,
    strip_latex_comment,
)
from .matcher import (
    discover_submissions,
    match_student_directory,
    normalize_student_id,
    record_from_latex_file,
)
from .models import (
    CompilationResult,
    ParsedSubmission,
    PdfPageArtifact,
    PdfRenderResult,
    SOURCE_LATEX,
    SOURCE_NONE,
    SOURCE_PDF,
    SUBMISSION_MODE_LATEX,
    SUBMISSION_MODE_PDF_ACCOMMODATION,
    SubmissionRecord,
)
from .parser import (
    parse_pdf_accommodation,
    parse_pdf_accommodations,
    parse_submission,
    parse_submissions_folder,
)
from .pdf import (
    DEFAULT_MAX_PAGE_PIXELS,
    DEFAULT_MAX_PDF_BYTES,
    DEFAULT_MAX_PDF_PAGES,
    DEFAULT_MIN_TEXT_CHARS_PER_PAGE,
    DEFAULT_RENDER_DPI,
    MAX_RENDER_DPI,
    MIN_RENDER_DPI,
    cleanup_pdf_render_artifacts,
    extract_text_from_pdf,
    record_from_pdf_accommodation,
    render_pdf_pages,
)
from .repository import (
    CANONICAL_DIRNAME,
    CANONICAL_REPOSITORY_SCHEMA_VERSION,
    DERIVED_DIRNAME,
    ORIGINALS_DIRNAME,
    STUDENT_INDEX_FILENAME,
    SUBMISSION_MANIFEST_FILENAME,
    CanonicalStoragePaths,
    SubmissionRepository,
    canonical_storage_paths,
)
from .sources import (
    LocalFileSourceAdapter,
    SubmissionSourceAdapter,
    discover_local_directory,
    discover_local_files,
)
from .splitter import (
    FULL_SUBMISSION,
    normalize_heading_question_id,
    split_answers_by_question,
)
from .reference_solution import (
    REFERENCE_SOLUTION_DIRNAME,
    ReferenceSolution,
    load_reference_solution,
    prepare_reference_solution,
    reference_solution_root,
)
from .storage import (
    EVIDENCE_SCHEMA_VERSION,
    EXTRACTED_ANSWERS_FILENAME,
    EvidenceStoragePaths,
    RAW_TEXT_FILENAME,
    SUBMISSION_META_FILENAME,
    TRANSCRIPTION_CACHE_FILENAME,
    TRANSCRIPTION_CACHE_SCHEMA_VERSION,
    TRANSCRIPTION_FILENAME,
    assessment_submission_fields,
    build_transcription_cache_inputs,
    compute_file_sha256,
    evidence_storage_paths,
    load_cached_transcription,
    load_persisted_submission,
    persist_submission_evidence,
    save_transcription_cache,
    transcription_cache_key,
)
from .transcription import (
    DEFAULT_HANDWRITING_MODEL,
    DEFAULT_KEEP_ALIVE,
    DEFAULT_MODEL_LOAD_TIMEOUT,
    DEFAULT_INFERENCE_TIMEOUT,
    DEFAULT_NUM_CTX,
    DEFAULT_NUM_PREDICT,
    DEFAULT_OLLAMA_URL,
    DEFAULT_SEED,
    DEFAULT_TEMPERATURE,
    HANDWRITING_PROMPT_SHA256,
    HANDWRITING_PROMPT_VERSION,
    HANDWRITING_TRANSCRIPTION_PROMPT,
    OllamaTranscriptionBackend,
    PageTranscription,
    TranscriptionBackend,
    TranscriptionBatchResult,
    TranscriptionPreflightResult,
    TranscriptionStatus,
    detect_degenerate_repetition,
    transcribe_page_images,
)


__all__ = [
    "ALLOWED_ENGINES",
    "DUPLICATE_STATUS_EXACT_ACTIVE",
    "DUPLICATE_STATUS_EXACT_HISTORICAL",
    "DUPLICATE_STATUS_EXISTING_NEW_ATTEMPT",
    "DUPLICATE_STATUS_IN_BATCH_EXACT",
    "DUPLICATE_STATUS_NONE",
    "DUPLICATE_STATUS_NOT_CHECKED",
    "DUPLICATE_STATUS_SAME_FILENAMES_CHANGED",
    "ImportCommitResult",
    "LocalFileSourceAdapter",
    "SubmissionImporter",
    "SubmissionSourceAdapter",
    "discover_local_directory",
    "discover_local_files",
    "CANONICAL_DIRNAME",
    "CANONICAL_REPOSITORY_SCHEMA_VERSION",
    "ArtifactFile",
    "CandidateFile",
    "CanonicalStoragePaths",
    "CompilationResult",
    "DEFAULT_HANDWRITING_MODEL",
    "DEFAULT_KEEP_ALIVE",
    "DEFAULT_INFERENCE_TIMEOUT",
    "DEFAULT_MODEL_LOAD_TIMEOUT",
    "DEFAULT_MAX_PAGE_PIXELS",
    "DEFAULT_MAX_PDF_BYTES",
    "DEFAULT_MAX_PDF_PAGES",
    "DEFAULT_MIN_TEXT_CHARS_PER_PAGE",
    "DEFAULT_NUM_CTX",
    "DEFAULT_NUM_PREDICT",
    "DEFAULT_OLLAMA_URL",
    "DEFAULT_RENDER_DPI",
    "DEFAULT_SEED",
    "DEFAULT_TEMPERATURE",
    "DerivedArtifact",
    "DERIVED_DIRNAME",
    "EVIDENCE_SCHEMA_VERSION",
    "EXTRACTED_ANSWERS_FILENAME",
    "EvidenceStoragePaths",
    "ExternalReference",
    "FULL_SUBMISSION",
    "HANDWRITING_PROMPT_SHA256",
    "HANDWRITING_PROMPT_VERSION",
    "HANDWRITING_TRANSCRIPTION_PROMPT",
    "ImportBatch",
    "ImportCandidate",
    "MAX_RENDER_DPI",
    "MIN_RENDER_DPI",
    "ORIGINALS_DIRNAME",
    "OllamaTranscriptionBackend",
    "PageTranscription",
    "ParsedSubmission",
    "PdfPageArtifact",
    "PdfRenderResult",
    "RAW_TEXT_FILENAME",
    "REFERENCE_SOLUTION_DIRNAME",
    "ReferenceSolution",
    "SOURCE_LATEX",
    "SOURCE_NONE",
    "SOURCE_PDF",
    "STUDENT_INDEX_FILENAME",
    "SUBMISSION_DOMAIN_SCHEMA_VERSION",
    "SUBMISSION_MANIFEST_FILENAME",
    "SUBMISSION_META_FILENAME",
    "SUBMISSION_MODE_LATEX",
    "SUBMISSION_MODE_PDF_ACCOMMODATION",
    "Submission",
    "SubmissionRepository",
    "SubmissionRecord",
    "TRANSCRIPTION_CACHE_FILENAME",
    "TRANSCRIPTION_CACHE_SCHEMA_VERSION",
    "TRANSCRIPTION_FILENAME",
    "TranscriptionBackend",
    "TranscriptionBatchResult",
    "TranscriptionPreflightResult",
    "TranscriptionStatus",
    "assessment_submission_fields",
    "build_transcription_cache_inputs",
    "canonical_storage_paths",
    "cleanup_compilation_artifacts",
    "cleanup_pdf_render_artifacts",
    "compute_file_sha256",
    "compile_tex_to_pdf",
    "detect_degenerate_repetition",
    "discover_submissions",
    "evidence_storage_paths",
    "extract_text_from_pdf",
    "extract_text_from_tex",
    "generate_artifact_id",
    "generate_candidate_id",
    "generate_derived_artifact_id",
    "generate_import_batch_id",
    "generate_submission_id",
    "load_cached_transcription",
    "load_persisted_submission",
    "load_reference_solution",
    "match_student_directory",
    "normalize_heading_question_id",
    "normalize_student_id",
    "parse_pdf_accommodation",
    "parse_pdf_accommodations",
    "parse_submission",
    "parse_submissions_folder",
    "persist_submission_evidence",
    "prepare_reference_solution",
    "record_from_latex_file",
    "record_from_pdf_accommodation",
    "reference_solution_root",
    "render_pdf_pages",
    "save_transcription_cache",
    "split_answers_by_question",
    "strip_latex_comment",
    "transcribe_page_images",
    "transcription_cache_key",
]
