"""Programming Submission & Autograding backend for the Rubric Grading Tool.

v2.3.3 Commits 1-3 provide domain/configuration contracts, immutable instructor
test-bundle storage, and a canonical-submission-to-execution-plan bridge.  They
do **not** execute student code, import Docker/pytest, or depend on PyQt.
"""

from .config import (
    AUTOGRADING_CONFIG_SCHEMA_VERSION,
    DEFAULT_REPORTING_POLICY,
    SCORING_METHOD_EQUAL_WITHIN_GROUP,
    SCORING_METHOD_EXPLICIT_TEST_POINTS,
    SUPPORTED_AUTOGRADING_LANGUAGES,
    SUPPORTED_AUTOGRADING_RUNNERS,
    SUPPORTED_SCORING_METHODS,
    AutogradingConfig,
    load_autograding_config,
    save_autograding_config,
)
from .bundle_store import (
    AUTOGRADING_DIRECTORY,
    BUNDLES_DIRECTORY,
    BUNDLE_INDEX_FILENAME,
    BUNDLE_INDEX_SCHEMA_VERSION,
    BUNDLE_MANIFEST_FILENAME,
    BUNDLE_ORIGINALS_DIRECTORY,
    TestBundleStore,
)
from .bundles import (
    BundleFile,
    BundleImportResult,
    StoredTestBundle,
    TEST_BUNDLE_FINGERPRINT_SCHEMA_VERSION,
    TEST_BUNDLE_MANIFEST_SCHEMA_VERSION,
    ValidatedTestBundle,
    validate_test_bundle,
)
from .errors import (
    AutogradingBundleError,
    AutogradingBundleIntegrityError,
    AutogradingBundleSelectionError,
    AutogradingBundleStorageError,
    AutogradingBundleValidationError,
    AutogradingError,
    AutogradingPlanningError,
    AutogradingSerializationError,
    AutogradingValidationError,
    CanonicalSubmissionIntegrityError,
    ExecutionPlanValidationError,
    NoCanonicalSubmissionError,
    ProgrammingSubmissionContractError,
    UnsupportedAutogradingLanguageError,
    UnsupportedAutogradingRunnerError,
    UnsupportedAutogradingSchemaError,
)
from .ids import (
    generate_autograding_run_id,
    generate_test_bundle_id,
)
from .planner import (
    EXECUTION_PLAN_SCHEMA_VERSION,
    ExecutionPlan,
    build_execution_plan,
    build_execution_plan_from_bundle,
)
from .submission_adapter import (
    PROGRAMMING_PATH_METADATA_KEY,
    ProgrammingSubmissionSelection,
    select_programming_submission,
)
from .workspace import (
    EXECUTION_WORKSPACE_SCHEMA_VERSION,
    GRADER_DIRECTORY,
    OUTPUT_DIRECTORY,
    SUBMISSION_DIRECTORY,
    WORKSPACE_NAMESPACE_GRADER,
    WORKSPACE_NAMESPACE_SUBMISSION,
    WORKSPACE_NAMESPACES,
    ExecutionWorkspaceSpec,
    PlannedWorkspaceFile,
    normalize_workspace_relative_path,
)
from .validation import (
    ALLOWED_TOP_LEVEL_ENTRIES,
    AUTOGRADER_CONFIG_FILENAME,
    DEFAULT_MAX_BUNDLE_FILE_BYTES,
    DEFAULT_MAX_BUNDLE_FILES,
    DEFAULT_MAX_BUNDLE_TOTAL_BYTES,
    IGNORED_BUNDLE_METADATA_FILENAMES,
    REQUIREMENTS_FILENAME,
    SUPPORT_DIRECTORY,
    TESTS_DIRECTORY,
    discover_test_function_names,
    normalize_bundle_relative_path,
    validate_declared_test_ids,
    validate_requirements_text,
)
from .models import *  # re-export stable domain constants and value objects
from .models import __all__ as _model_all


__all__ = list(_model_all) + [
    "ALLOWED_TOP_LEVEL_ENTRIES",
    "AUTOGRADER_CONFIG_FILENAME",
    "AUTOGRADING_DIRECTORY",
    "AutogradingBundleError",
    "AutogradingBundleIntegrityError",
    "AutogradingBundleSelectionError",
    "AutogradingBundleStorageError",
    "AutogradingBundleValidationError",
    "BUNDLES_DIRECTORY",
    "BUNDLE_INDEX_FILENAME",
    "BUNDLE_INDEX_SCHEMA_VERSION",
    "BUNDLE_MANIFEST_FILENAME",
    "BUNDLE_ORIGINALS_DIRECTORY",
    "BundleFile",
    "BundleImportResult",
    "DEFAULT_MAX_BUNDLE_FILE_BYTES",
    "DEFAULT_MAX_BUNDLE_FILES",
    "DEFAULT_MAX_BUNDLE_TOTAL_BYTES",
    "IGNORED_BUNDLE_METADATA_FILENAMES",
    "REQUIREMENTS_FILENAME",
    "StoredTestBundle",
    "SUPPORT_DIRECTORY",
    "TESTS_DIRECTORY",
    "TEST_BUNDLE_FINGERPRINT_SCHEMA_VERSION",
    "TEST_BUNDLE_MANIFEST_SCHEMA_VERSION",
    "TestBundleStore",
    "ValidatedTestBundle",
    "discover_test_function_names",
    "normalize_bundle_relative_path",
    "validate_declared_test_ids",
    "validate_requirements_text",
    "validate_test_bundle",
    "AUTOGRADING_CONFIG_SCHEMA_VERSION",
    "AutogradingConfig",
    "AutogradingError",
    "AutogradingPlanningError",
    "AutogradingSerializationError",
    "AutogradingValidationError",
    "CanonicalSubmissionIntegrityError",
    "ExecutionPlanValidationError",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "EXECUTION_WORKSPACE_SCHEMA_VERSION",
    "ExecutionPlan",
    "ExecutionWorkspaceSpec",
    "GRADER_DIRECTORY",
    "NoCanonicalSubmissionError",
    "OUTPUT_DIRECTORY",
    "PROGRAMMING_PATH_METADATA_KEY",
    "PlannedWorkspaceFile",
    "ProgrammingSubmissionContractError",
    "ProgrammingSubmissionSelection",
    "SUBMISSION_DIRECTORY",
    "WORKSPACE_NAMESPACE_GRADER",
    "WORKSPACE_NAMESPACE_SUBMISSION",
    "WORKSPACE_NAMESPACES",
    "build_execution_plan",
    "build_execution_plan_from_bundle",
    "normalize_workspace_relative_path",
    "select_programming_submission",
    "DEFAULT_REPORTING_POLICY",
    "SCORING_METHOD_EQUAL_WITHIN_GROUP",
    "SCORING_METHOD_EXPLICIT_TEST_POINTS",
    "SUPPORTED_AUTOGRADING_LANGUAGES",
    "SUPPORTED_AUTOGRADING_RUNNERS",
    "SUPPORTED_SCORING_METHODS",
    "UnsupportedAutogradingLanguageError",
    "UnsupportedAutogradingRunnerError",
    "UnsupportedAutogradingSchemaError",
    "generate_autograding_run_id",
    "generate_test_bundle_id",
    "load_autograding_config",
    "save_autograding_config",
]
