"""Qt thread-pool worker for submission ingestion and transcription.

This module contains *orchestration only*.  It deliberately delegates all
LaTeX/PDF parsing, persistence, cache reuse, and handwriting transcription to
``SubmissionController`` and the already-tested ``src.submissions`` backend.
No parser/transcription logic is duplicated here.

The worker never registers parsed results in ``SubmissionController``.  Qt UI
code must do that after receiving ``completed`` on the GUI thread.  This keeps
controller/session state single-threaded and also makes stale-result handling
straightforward: every signal carries an opaque ``request_id`` plus the target
student ID and operation.
"""

from __future__ import annotations

from enum import Enum
import threading
import uuid
from typing import Any, Callable, Dict, Mapping, Optional

from PyQt5.QtCore import QObject, QRunnable, pyqtSignal, pyqtSlot

from src.submissions import (
    DEFAULT_HANDWRITING_MODEL,
    OllamaTranscriptionBackend,
)
from src.ui.submission_controller import SubmissionController


class SubmissionOperation(str, Enum):
    """Supported background operations."""

    LOAD_NORMAL_SUBMISSIONS = "load_normal_submissions"
    LOAD_PDF_ACCOMMODATION = "load_pdf_accommodation"
    GENERATE_TRANSCRIPTION = "generate_transcription"
    REFRESH_TRANSCRIPTION = "refresh_transcription"
    TEST_OLLAMA = "test_ollama"


def new_request_id() -> str:
    """Return an opaque token suitable for stale-result protection."""

    return uuid.uuid4().hex


def _normalize_operation(value: Any) -> SubmissionOperation:
    if isinstance(value, SubmissionOperation):
        return value
    try:
        return SubmissionOperation(str(value))
    except ValueError as exc:
        choices = ", ".join(item.value for item in SubmissionOperation)
        raise ValueError(f"Unknown submission operation {value!r}; expected one of: {choices}") from exc


class SubmissionWorkerSignals(QObject):
    """Signals emitted by :class:`SubmissionWorker`.

    Signal fields are positional to make connections lightweight:

    ``started(request_id, student_id, operation)``
    ``progress(request_id, student_id, operation, message)``
    ``completed(request_id, student_id, operation, payload)``
    ``failed(request_id, student_id, operation, error_type, error_message)``
    ``cancelled(request_id, student_id, operation)``
    ``finished(request_id, student_id, operation)``

    ``payload`` is operation-specific: a mapping of student IDs to
    ``ParsedSubmission`` objects, one ``ParsedSubmission``, or a
    ``TranscriptionPreflightResult`` for ``TEST_OLLAMA``.
    """

    started = pyqtSignal(str, str, str)
    progress = pyqtSignal(str, str, str, str)
    completed = pyqtSignal(str, str, str, object)
    failed = pyqtSignal(str, str, str, str, str)
    cancelled = pyqtSignal(str, str, str)
    finished = pyqtSignal(str, str, str)


class SubmissionWorker(QRunnable):
    """Execute one submission operation in a ``QThreadPool``.

    Parameters
    ----------
    controller:
        Current ``SubmissionController``.  Required for all operations except
        ``TEST_OLLAMA``.  Its parse helpers do not mutate controller state.
    operation:
        A ``SubmissionOperation`` value or its string representation.
    student_id:
        Target student for per-student PDF/transcription operations.  Normal
        folder loading and connection tests may leave this empty.
    request_id:
        Optional caller-owned stale-result token.  A UUID token is generated by
        default.
    parameters:
        Backend/controller keyword arguments.  See ``_execute`` below for the
        intentionally small supported contract.
    backend_factory:
        Injectable for tests.  Defaults to ``OllamaTranscriptionBackend``.
    """

    def __init__(
        self,
        controller: Optional[SubmissionController],
        operation: Any,
        *,
        student_id: Optional[str] = None,
        request_id: Optional[str] = None,
        parameters: Optional[Mapping[str, Any]] = None,
        backend_factory: Callable[..., Any] = OllamaTranscriptionBackend,
    ) -> None:
        super().__init__()
        self.controller = controller
        self.operation = _normalize_operation(operation)
        self.student_id = str(student_id or "").strip()
        self.request_id = str(request_id or new_request_id())
        self.parameters: Dict[str, Any] = dict(parameters or {})
        self.backend_factory = backend_factory
        self.signals = SubmissionWorkerSignals()
        self._cancel_event = threading.Event()
        self.setAutoDelete(True)

        if self.operation != SubmissionOperation.TEST_OLLAMA and self.controller is None:
            raise ValueError(f"controller is required for operation {self.operation.value!r}")
        if self.operation in {
            SubmissionOperation.LOAD_PDF_ACCOMMODATION,
            SubmissionOperation.GENERATE_TRANSCRIPTION,
            SubmissionOperation.REFRESH_TRANSCRIPTION,
        } and not self.student_id:
            raise ValueError(f"student_id is required for operation {self.operation.value!r}")

    def cancel(self) -> None:
        """Request cooperative cancellation.

        Existing parser/Ollama calls are not forcefully interrupted.  If a
        request is cancelled while one of those calls is in progress, its
        eventual result is suppressed and ``cancelled`` is emitted instead.
        """

        self._cancel_event.set()

    @property
    def is_cancelled(self) -> bool:
        return self._cancel_event.is_set()

    def _emit_progress(self, message: str) -> None:
        self.signals.progress.emit(
            self.request_id,
            self.student_id,
            self.operation.value,
            str(message),
        )

    @pyqtSlot()
    def run(self) -> None:
        """Run the operation.  Intended for ``QThreadPool.start(worker)``."""

        operation = self.operation.value
        self.signals.started.emit(self.request_id, self.student_id, operation)
        try:
            if self.is_cancelled:
                self.signals.cancelled.emit(self.request_id, self.student_id, operation)
                return

            payload = self._execute()

            if self.is_cancelled:
                self.signals.cancelled.emit(self.request_id, self.student_id, operation)
                return

            self.signals.completed.emit(
                self.request_id,
                self.student_id,
                operation,
                payload,
            )
        except Exception as exc:  # Worker boundary: convert backend errors to a UI-safe signal.
            self.signals.failed.emit(
                self.request_id,
                self.student_id,
                operation,
                type(exc).__name__,
                str(exc) or type(exc).__name__,
            )
        finally:
            self.signals.finished.emit(self.request_id, self.student_id, operation)

    # ------------------------------------------------------------------
    # Operation dispatch
    # ------------------------------------------------------------------

    def _execute(self) -> Any:
        if self.operation == SubmissionOperation.LOAD_NORMAL_SUBMISSIONS:
            return self._load_normal_submissions()
        if self.operation == SubmissionOperation.LOAD_PDF_ACCOMMODATION:
            return self._load_pdf_accommodation(transcribe=False, refresh=False)
        if self.operation == SubmissionOperation.GENERATE_TRANSCRIPTION:
            return self._load_pdf_accommodation(transcribe=True, refresh=False)
        if self.operation == SubmissionOperation.REFRESH_TRANSCRIPTION:
            return self._load_pdf_accommodation(transcribe=True, refresh=True)
        if self.operation == SubmissionOperation.TEST_OLLAMA:
            return self._test_ollama()
        raise AssertionError(f"Unhandled operation: {self.operation!r}")

    def _load_normal_submissions(self) -> Any:
        parameters = dict(self.parameters)
        submissions_dir = parameters.pop("submissions_dir", None)
        if not submissions_dir:
            raise ValueError("submissions_dir is required for normal submission loading")
        self._emit_progress("Preparing LaTeX submissions…")
        return self.controller.parse_normal_submissions(  # type: ignore[union-attr]
            str(submissions_dir),
            **parameters,
        )

    def _load_pdf_accommodation(self, *, transcribe: bool, refresh: bool) -> Any:
        parameters = dict(self.parameters)
        pdf_path = parameters.pop("pdf_path", None)
        if not pdf_path:
            raise ValueError("pdf_path is required for PDF accommodation work")

        # These are UI connection settings, not parser options.
        base_url = parameters.pop("base_url", None)
        model = parameters.pop("model", None)
        explicit_backend = parameters.pop("transcription_backend", None)

        if transcribe:
            backend = explicit_backend
            if backend is None:
                backend_kwargs: Dict[str, Any] = {}
                if base_url:
                    backend_kwargs["base_url"] = str(base_url)
                if model:
                    backend_kwargs["model"] = str(model)
                backend = self.backend_factory(**backend_kwargs)
            parameters["transcription_backend"] = backend
            parameters["transcribe_handwriting"] = True
            # Generate is cache-first; Refresh explicitly performs a new pass.
            parameters["reuse_cached_transcription"] = not refresh
            self._emit_progress(
                "Refreshing assistive transcription…"
                if refresh
                else "Generating assistive transcription…"
            )
        else:
            # Loading/rendering an explicit accommodation must never silently
            # trigger VLM inference.
            parameters.pop("reuse_cached_transcription", None)
            parameters["transcribe_handwriting"] = False
            parameters["transcription_backend"] = None
            self._emit_progress("Preparing PDF accommodation evidence…")

        return self.controller.parse_pdf_accommodation(  # type: ignore[union-attr]
            self.student_id,
            str(pdf_path),
            **parameters,
        )

    def _test_ollama(self) -> Any:
        parameters = dict(self.parameters)
        base_url = parameters.pop("base_url", None)
        model = parameters.pop("model", None) or DEFAULT_HANDWRITING_MODEL
        backend_kwargs: Dict[str, Any] = {"model": str(model)}
        if base_url:
            backend_kwargs["base_url"] = str(base_url)
        # Keep production defaults authoritative.  The UI exposes only endpoint
        # and model; test code may inject a fake factory.
        self._emit_progress("Testing Ollama connection…")
        backend = self.backend_factory(**backend_kwargs)
        return backend.preflight(force=True)


__all__ = [
    "SubmissionOperation",
    "SubmissionWorker",
    "SubmissionWorkerSignals",
    "new_request_id",
]
