"""Backend support for Overleaf / multi-file LaTeX project ingestion.

v2.3.4.2 Commit 7 adds restart-safe provenance, structured diagnostics, and
verified recovery on top of the Commit-6 Written ZIP workflow. Original ZIPs
and canonical submission manifests remain immutable; mutable recovery state is
kept only under the derived LaTeX-project tree.
"""

from .archive import (
    LatexArchiveExtractionSummary,
    compute_manifest_sha256,
    safe_extract_latex_project_zip,
)
from .compilation import (
    LatexProjectCompilation,
    compile_stored_latex_project_to_pdf,
)
from .discovery import (
    LatexProjectDiscovery,
    LatexProjectReference,
    LatexTexSourceInfo,
    discover_latex_project,
)
from .config import (
    DEFAULT_IGNORED_DIRECTORY_NAMES,
    DEFAULT_IGNORED_METADATA_NAMES,
    DEFAULT_MAX_ARCHIVE_BYTES,
    DEFAULT_MAX_COMPRESSION_RATIO,
    DEFAULT_MAX_FILE_COUNT,
    DEFAULT_MAX_INCLUDE_DEPTH,
    DEFAULT_MAX_MEMBER_BYTES,
    DEFAULT_MAX_TOTAL_UNCOMPRESSED_BYTES,
    DEFAULT_PREFERRED_ROOT_NAMES,
    LATEX_PROJECT_CONFIG_SCHEMA_VERSION,
    LatexProjectIngestionConfig,
    LatexProjectSafetyLimits,
    load_latex_project_config,
    save_latex_project_config,
)
from .errors import (
    LatexProjectArchiveError,
    LatexProjectArchiveRejectedError,
    LatexProjectError,
    LatexProjectIntegrityError,
    LatexProjectSerializationError,
    LatexProjectStorageError,
    LatexProjectValidationError,
    UnsupportedLatexProjectSchemaError,
)
from .import_preview import (
    LATEX_PROJECT_PREVIEW_METADATA_KEY,
    LATEX_PROJECT_ROOT_METADATA_KEY,
    LATEX_PROJECT_ROOT_METHOD_METADATA_KEY,
    ROOT_SELECTION_DETERMINISTIC,
    ROOT_SELECTION_INSTRUCTOR,
    LatexProjectImportPreview,
    apply_latex_project_preview_validation,
    candidate_latex_project_preview,
    inspect_latex_project_zip,
    latex_project_root_selection_required,
    preflight_latex_project_candidate,
    preflight_latex_project_candidates,
    set_candidate_latex_project_root,
)
from .models import *  # re-export stable domain constants/value objects
from .models import __all__ as _model_all
from .resolution import (
    resolve_latex_project_root,
    select_latex_project_root,
)
from .provenance import (
    LATEX_PROJECT_LOGS_DIRNAME,
    LATEX_PROJECT_PROVENANCE_FILENAME,
    LATEX_PROJECT_PROVENANCE_SCHEMA_VERSION,
    PROJECT_STATUS_COMPILED,
    PROJECT_STATUS_COMPILATION_FAILED,
    PROJECT_STATUS_INTEGRITY_FAILED,
    PROJECT_STATUS_ROOT_RESOLVED,
    LatexProjectCompilationAttempt,
    LatexProjectProvenanceState,
    append_compilation_attempt,
    load_latex_project_provenance,
    provenance_diagnostic_payload,
    provenance_path,
    reusable_compiled_pdf,
    save_latex_project_provenance,
    state_with_resolution,
)
from .written_bridge import (
    LATEX_PROJECT_COMPILED_DIRNAME,
    LATEX_PROJECT_DERIVED_DIRNAME,
    LatexProjectCompilationFailedError,
    LatexProjectPreparedContext,
    LatexProjectRootResolutionRequiredError,
    LatexProjectWrittenBridgeError,
    canonical_latex_project_diagnostic,
    parse_canonical_latex_project,
    prepare_canonical_latex_project,
)
from .storage import (
    ARCHIVE_METADATA_FILENAME,
    EXTRACTED_DIRNAME,
    MANIFEST_FILENAME,
    ORIGINAL_ARCHIVE_FILENAME,
    ORIGINAL_DIRNAME,
    LatexProjectArchiveStore,
    StoredLatexProject,
    verify_stored_latex_project,
)


__all__ = list(_model_all) + [
    "LATEX_PROJECT_PREVIEW_METADATA_KEY",
    "LATEX_PROJECT_ROOT_METADATA_KEY",
    "LATEX_PROJECT_ROOT_METHOD_METADATA_KEY",
    "ROOT_SELECTION_DETERMINISTIC",
    "ROOT_SELECTION_INSTRUCTOR",
    "LatexProjectImportPreview",
    "apply_latex_project_preview_validation",
    "candidate_latex_project_preview",
    "inspect_latex_project_zip",
    "latex_project_root_selection_required",
    "preflight_latex_project_candidate",
    "preflight_latex_project_candidates",
    "set_candidate_latex_project_root",
    "LATEX_PROJECT_LOGS_DIRNAME",
    "LATEX_PROJECT_PROVENANCE_FILENAME",
    "LATEX_PROJECT_PROVENANCE_SCHEMA_VERSION",
    "PROJECT_STATUS_COMPILED",
    "PROJECT_STATUS_COMPILATION_FAILED",
    "PROJECT_STATUS_INTEGRITY_FAILED",
    "PROJECT_STATUS_ROOT_RESOLVED",
    "LatexProjectCompilationAttempt",
    "LatexProjectProvenanceState",
    "append_compilation_attempt",
    "load_latex_project_provenance",
    "provenance_diagnostic_payload",
    "provenance_path",
    "reusable_compiled_pdf",
    "save_latex_project_provenance",
    "state_with_resolution",
    "ARCHIVE_METADATA_FILENAME",
    "DEFAULT_IGNORED_DIRECTORY_NAMES",
    "DEFAULT_IGNORED_METADATA_NAMES",
    "DEFAULT_MAX_ARCHIVE_BYTES",
    "DEFAULT_MAX_COMPRESSION_RATIO",
    "DEFAULT_MAX_FILE_COUNT",
    "DEFAULT_MAX_INCLUDE_DEPTH",
    "DEFAULT_MAX_MEMBER_BYTES",
    "DEFAULT_MAX_TOTAL_UNCOMPRESSED_BYTES",
    "DEFAULT_PREFERRED_ROOT_NAMES",
    "EXTRACTED_DIRNAME",
    "LATEX_PROJECT_CONFIG_SCHEMA_VERSION",
    "LatexArchiveExtractionSummary",
    "LatexProjectDiscovery",
    "LatexProjectReference",
    "LatexTexSourceInfo",
    "LatexProjectArchiveError",
    "LatexProjectArchiveRejectedError",
    "LatexProjectArchiveStore",
    "LatexProjectCompilation",
    "LATEX_PROJECT_COMPILED_DIRNAME",
    "LATEX_PROJECT_DERIVED_DIRNAME",
    "LatexProjectCompilationFailedError",
    "LatexProjectPreparedContext",
    "LatexProjectRootResolutionRequiredError",
    "LatexProjectWrittenBridgeError",
    "canonical_latex_project_diagnostic",
    "LatexProjectError",
    "LatexProjectIngestionConfig",
    "LatexProjectIntegrityError",
    "LatexProjectSafetyLimits",
    "LatexProjectSerializationError",
    "LatexProjectStorageError",
    "LatexProjectValidationError",
    "MANIFEST_FILENAME",
    "ORIGINAL_ARCHIVE_FILENAME",
    "ORIGINAL_DIRNAME",
    "StoredLatexProject",
    "UnsupportedLatexProjectSchemaError",
    "compile_stored_latex_project_to_pdf",
    "parse_canonical_latex_project",
    "prepare_canonical_latex_project",
    "compute_manifest_sha256",
    "discover_latex_project",
    "resolve_latex_project_root",
    "select_latex_project_root",
    "load_latex_project_config",
    "safe_extract_latex_project_zip",
    "save_latex_project_config",
    "verify_stored_latex_project",
]
